export interface MockProduct {
  id: string;
  name: string;
  slug: string;
  description: string;
  price: number;
  category: string;
  categoryId: string;
  brand?: string;
  model?: string;
  stock: number;
  image?: string;
  specifications: { name: string; value: string }[];
  createdAt: string;
}

export const MOCK_PRODUCTS: MockProduct[] = [
  // ── Computación ─────────────────────────────────────────────
  {
    id: 'macbook-pro-14',
    name: 'MacBook Pro 14" M4 Pro',
    slug: 'macbook-pro-14-m4-pro',
    description: 'MacBook Pro de 14 pulgadas con chip M4 Pro de Apple. Pantalla Liquid Retina XDR, 24GB de memoria unificada, SSD de 512GB y hasta 22 horas de batería. Ideal para profesionales creativos y desarrolladores.',
    price: 7999999,
    category: 'Computación',
    categoryId: 'computacion',
    brand: 'Apple',
    model: 'M4 Pro',
    stock: 8,
    image: 'https://images.unsplash.com/photo-1537498425277-c283d32ef9db?ixlib=rb-4.1.0&q=85&fm=jpg&crop=entropy&cs=srgb&dl=kari-shea-vjMgqUkS8q8-unsplash.jpg',
    specifications: [
      { name: 'Chip', value: 'Apple M4 Pro' },
      { name: 'Pantalla', value: '14.2" Liquid Retina XDR' },
      { name: 'Memoria', value: '24GB Unificada' },
      { name: 'Almacenamiento', value: '512GB SSD' },
      { name: 'Batería', value: 'Hasta 22 horas' },
      { name: 'Puertos', value: '3x Thunderbolt 4, HDMI, SDXC' },
      { name: 'Peso', value: '1.61 kg' },
    ],
    createdAt: '2025-03-15',
  },
  {
    id: 'macbook-air-15',
    name: 'MacBook Air 15" M3',
    slug: 'macbook-air-15-m3',
    description: 'MacBook Air de 15 pulgadas con chip M3. Ultra delgada y liviana, perfecta para el día a día. Pantalla Liquid Retina, 16GB de memoria unificada y SSD de 256GB.',
    price: 5499999,
    category: 'Computación',
    categoryId: 'computacion',
    brand: 'Apple',
    model: 'M3',
    stock: 12,
    image: 'https://images.unsplash.com/photo-1499673610122-01c7122c5dcb?w=800&h=1000&fit=crop',
    specifications: [
      { name: 'Chip', value: 'Apple M3' },
      { name: 'Pantalla', value: '15.3" Liquid Retina' },
      { name: 'Memoria', value: '16GB Unificada' },
      { name: 'Almacenamiento', value: '256GB SSD' },
      { name: 'Batería', value: 'Hasta 18 horas' },
      { name: 'Peso', value: '1.51 kg' },
    ],
    createdAt: '2025-02-10',
  },
  {
    id: 'macbook-pro-16',
    name: 'MacBook Pro 16" M4 Max',
    slug: 'macbook-pro-16-m4-max',
    description: 'La MacBook Pro más potente. Chip M4 Max con CPU de 16 núcleos y GPU de 40 núcleos. Pantalla Liquid Retina XDR de 16 pulgadas, 48GB de memoria y SSD de 1TB.',
    price: 11999999,
    category: 'Computación',
    categoryId: 'computacion',
    brand: 'Apple',
    model: 'M4 Max',
    stock: 3,
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?ixlib=rb-4.1.0&q=85&fm=jpg&crop=entropy&cs=srgb&dl=alex-tkachenko-1SAnrIxw5OY-unsplash.jpg',
    specifications: [
      { name: 'Chip', value: 'Apple M4 Max' },
      { name: 'Pantalla', value: '16.2" Liquid Retina XDR' },
      { name: 'Memoria', value: '48GB Unificada' },
      { name: 'Almacenamiento', value: '1TB SSD' },
      { name: 'Batería', value: 'Hasta 22 horas' },
      { name: 'Puertos', value: '3x Thunderbolt 4, HDMI, SDXC' },
      { name: 'Peso', value: '2.14 kg' },
    ],
    createdAt: '2025-03-20',
  },
  {
    id: 'imac-24-m4',
    name: 'iMac 24" M4',
    slug: 'imac-24-m4',
    description: 'iMac de 24 pulgadas con chip M4. Diseño icónico en 7 colores vibrantes. Pantalla 4.5K Retina, 16GB de memoria y SSD de 256GB. Perfecto para el hogar y la oficina.',
    price: 6299999,
    category: 'Computación',
    categoryId: 'computacion',
    brand: 'Apple',
    model: 'M4',
    stock: 6,
    image: 'https://images.unsplash.com/photo-1616763355603-9755a640a287?w=800&h=1000&fit=crop',
    specifications: [
      { name: 'Chip', value: 'Apple M4' },
      { name: 'Pantalla', value: '24" 4.5K Retina' },
      { name: 'Memoria', value: '16GB Unificada' },
      { name: 'Almacenamiento', value: '256GB SSD' },
      { name: 'Cámara', value: '1080p FaceTime HD' },
      { name: 'Colores', value: '7 colores' },
    ],
    createdAt: '2025-01-28',
  },
  {
    id: 'mac-mini-m4',
    name: 'Mac mini M4 Pro',
    slug: 'mac-mini-m4-pro',
    description: 'Mac mini con chip M4 Pro. Potencia increíble en un formato ultracompacto. Ideal para desarrolladores, creadores y cualquier persona que necesite rendimiento profesional.',
    price: 3299999,
    category: 'Computación',
    categoryId: 'computacion',
    brand: 'Apple',
    model: 'M4 Pro',
    stock: 15,
    image: 'https://images.unsplash.com/photo-1758857087569-83791ac9edd5?w=800&h=1000&fit=crop',
    specifications: [
      { name: 'Chip', value: 'Apple M4 Pro' },
      { name: 'Memoria', value: '24GB Unificada' },
      { name: 'Almacenamiento', value: '512GB SSD' },
      { name: 'Puertos', value: '3x Thunderbolt 4, HDMI, USB-A' },
      { name: 'Conectividad', value: 'WiFi 6E, Bluetooth 5.3' },
      { name: 'Peso', value: '670 g' },
    ],
    createdAt: '2025-04-05',
  },
  {
    id: 'ipad-pro-m4',
    name: 'iPad Pro M4 13"',
    slug: 'ipad-pro-m4-13',
    description: 'iPad Pro de 13 pulgadas con chip M4. La pantalla Ultra Retina XDR con tecnología tandem OLED es la más avanzada del mercado. Compatible con Apple Pencil Pro y Magic Keyboard.',
    price: 5799999,
    category: 'Computación',
    categoryId: 'computacion',
    brand: 'Apple',
    model: 'M4',
    stock: 7,
    image: 'https://images.unsplash.com/photo-1648806030599-c963fd14a22f?w=800&h=1000&fit=crop',
    specifications: [
      { name: 'Chip', value: 'Apple M4' },
      { name: 'Pantalla', value: '13" Ultra Retina XDR' },
      { name: 'Almacenamiento', value: '256GB' },
      { name: 'Cámara', value: '12MP + LiDAR' },
      { name: 'Conectividad', value: 'WiFi 6E, Bluetooth 5.3' },
      { name: 'Peso', value: '579 g' },
    ],
    createdAt: '2025-02-18',
  },
  {
    id: 'ipad-air-m2',
    name: 'iPad Air M2 11"',
    slug: 'ipad-air-m2-11',
    description: 'iPad Air de 11 pulgadas con chip M2. Pantalla Liquid Retina, 128GB de almacenamiento y compatibilidad con Apple Pencil Pro. El equilibrio perfecto entre rendimiento y precio.',
    price: 3499999,
    category: 'Computación',
    categoryId: 'computacion',
    brand: 'Apple',
    model: 'M2',
    stock: 10,
    image: 'https://images.unsplash.com/photo-1682427286841-1f3ff788752b?w=800&h=1000&fit=crop',
    specifications: [
      { name: 'Chip', value: 'Apple M2' },
      { name: 'Pantalla', value: '11" Liquid Retina' },
      { name: 'Almacenamiento', value: '128GB' },
      { name: 'Cámara', value: '12MP' },
      { name: 'Conectividad', value: 'WiFi 6, Bluetooth 5.0' },
      { name: 'Peso', value: '462 g' },
    ],
    createdAt: '2025-01-15',
  },
  {
    id: 'ipad-10-gen',
    name: 'iPad 10ª Gen',
    slug: 'ipad-10-gen',
    description: 'iPad de 10ª generación. Pantalla Liquid Retina de 10.9 pulgadas, chip A14 Bionic, 64GB de almacenamiento. USB-C y cámara frontal ultra gran angular con encuadre centrado.',
    price: 2299999,
    category: 'Computación',
    categoryId: 'computacion',
    brand: 'Apple',
    model: 'A14 Bionic',
    stock: 0,
    image: 'https://images.unsplash.com/photo-1630331528526-7d04c6eb463f?w=800&h=1000&fit=crop',
    specifications: [
      { name: 'Chip', value: 'A14 Bionic' },
      { name: 'Pantalla', value: '10.9" Liquid Retina' },
      { name: 'Almacenamiento', value: '64GB' },
      { name: 'Cámara', value: '12MP' },
      { name: 'Conector', value: 'USB-C' },
      { name: 'Peso', value: '477 g' },
    ],
    createdAt: '2024-10-20',
  },

  // ── Electrónica: iPhones ────────────────────────────────────
  {
    id: 'iphone-16-pro-max',
    name: 'iPhone 16 Pro Max 256GB',
    slug: 'iphone-16-pro-max-256gb',
    description: 'El iPhone más avanzado. Chip A18 Pro, pantalla Super Retina XDR de 6.9 pulgadas con ProMotion. Sistema de cámaras Pro de 48MP con zoom óptico 5x. Titanio grado aeroespacial.',
    price: 6999999,
    category: 'Electrónica',
    categoryId: 'electronica',
    brand: 'Apple',
    model: 'A18 Pro',
    stock: 10,
    image: 'https://images.unsplash.com/photo-1527334919515-b8dee906a34b?w=800&h=1000&fit=crop',
    specifications: [
      { name: 'Chip', value: 'A18 Pro' },
      { name: 'Pantalla', value: '6.9" Super Retina XDR' },
      { name: 'Almacenamiento', value: '256GB' },
      { name: 'Cámara Principal', value: '48MP Fusion' },
      { name: 'Zoom', value: 'Óptico 5x' },
      { name: 'Material', value: 'Titanio' },
      { name: 'Batería', value: 'Hasta 33 horas' },
    ],
    createdAt: '2025-03-10',
  },
  {
    id: 'iphone-16-pro',
    name: 'iPhone 16 Pro 128GB',
    slug: 'iphone-16-pro-128gb',
    description: 'iPhone 16 Pro con chip A18 Pro. Pantalla de 6.3 pulgadas, cámara de 48MP con ultra gran angular y teleobjetivo 3x. Diseño en titanio y botón de acción personalizable.',
    price: 5999999,
    category: 'Electrónica',
    categoryId: 'electronica',
    brand: 'Apple',
    model: 'A18 Pro',
    stock: 14,
    image: 'https://images.unsplash.com/photo-1726587912121-ea21fcc57ff8?ixlib=rb-4.1.0&q=85&fm=jpg&crop=entropy&cs=srgb&dl=igor-omilaev-lDWTfYhZ85w-unsplash.jpg',
    specifications: [
      { name: 'Chip', value: 'A18 Pro' },
      { name: 'Pantalla', value: '6.3" Super Retina XDR' },
      { name: 'Almacenamiento', value: '128GB' },
      { name: 'Cámara Principal', value: '48MP Fusion' },
      { name: 'Zoom', value: 'Óptico 3x' },
      { name: 'Material', value: 'Titanio' },
      { name: 'Batería', value: 'Hasta 27 horas' },
    ],
    createdAt: '2025-03-10',
  },
  {
    id: 'iphone-16',
    name: 'iPhone 16 128GB',
    slug: 'iphone-16-128gb',
    description: 'iPhone 16 con chip A18. Pantalla Super Retina XDR de 6.1 pulgadas. Cámara Fusion de 48MP con gran angular y ultra gran angular. Botón de acción y cámara vertical para grabación espacial.',
    price: 4499999,
    category: 'Electrónica',
    categoryId: 'electronica',
    brand: 'Apple',
    model: 'A18',
    stock: 20,
    image: 'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?ixlib=rb-4.1.0&q=85&fm=jpg&crop=entropy&cs=srgb&dl=bagus-hernawan-A6JxK37IlPo-unsplash.jpg',
    specifications: [
      { name: 'Chip', value: 'A18' },
      { name: 'Pantalla', value: '6.1" Super Retina XDR' },
      { name: 'Almacenamiento', value: '128GB' },
      { name: 'Cámara Principal', value: '48MP Fusion' },
      { name: 'Ultra Gran Angular', value: '12MP' },
      { name: 'Batería', value: 'Hasta 22 horas' },
    ],
    createdAt: '2025-03-10',
  },

  // ── Electrónica: Wearables ──────────────────────────────────
  {
    id: 'apple-watch-ultra-2',
    name: 'Apple Watch Ultra 2',
    slug: 'apple-watch-ultra-2',
    description: 'Apple Watch Ultra 2 con chip S9. Caja de titanio de 49mm, pantalla más brillante (3000 nits), botón de acción personalizable, GPS de doble frecuencia y hasta 36 horas de batería.',
    price: 3499999,
    category: 'Electrónica',
    categoryId: 'electronica',
    brand: 'Apple',
    model: 'Ultra 2',
    stock: 5,
    image: 'https://images.unsplash.com/photo-1617043786394-f977fa12eddf?w=800&h=1000&fit=crop',
    specifications: [
      { name: 'Chip', value: 'Apple S9' },
      { name: 'Pantalla', value: '49mm, 3000 nits' },
      { name: 'Material', value: 'Titanio' },
      { name: 'GPS', value: 'Doble frecuencia' },
      { name: 'Batería', value: 'Hasta 36 horas' },
      { name: 'Resistencia', value: '100m (EN13319)' },
    ],
    createdAt: '2025-01-25',
  },
  {
    id: 'apple-watch-series-9',
    name: 'Apple Watch Series 9',
    slug: 'apple-watch-series-9',
    description: 'Apple Watch Series 9 con chip S9. Procesamiento de Siri en dispositivo, gesto con doble toque, pantalla siempre activa y todas las funciones de salud y actividad física.',
    price: 2299999,
    category: 'Electrónica',
    categoryId: 'electronica',
    brand: 'Apple',
    model: 'Series 9',
    stock: 11,
    image: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?ixlib=rb-4.1.0&q=85&fm=jpg&crop=entropy&cs=srgb&dl=luke-chesser-rCOWMC8qf8A-unsplash.jpg',
    specifications: [
      { name: 'Chip', value: 'Apple S9' },
      { name: 'Pantalla', value: 'Siempre activa' },
      { name: 'Sensor', value: 'Oxímetro + ECG' },
      { name: 'GPS', value: 'Integrado' },
      { name: 'Batería', value: 'Hasta 18 horas' },
    ],
    createdAt: '2025-01-15',
  },
  {
    id: 'airpods-pro-2',
    name: 'AirPods Pro 2',
    slug: 'airpods-pro-2',
    description: 'AirPods Pro de 2ª generación. Cancelación activa de ruido 2x más efectiva, modo adaptativo, audio espacial personalizado y estuche MagSafe con altavoz integrado y USB-C.',
    price: 999999,
    category: 'Electrónica',
    categoryId: 'electronica',
    brand: 'Apple',
    model: 'AirPods Pro 2',
    stock: 25,
    image: 'https://images.unsplash.com/photo-1754142654807-1dfcdc3f7f22?w=800&h=1000&fit=crop',
    specifications: [
      { name: 'Chip', value: 'Apple H2' },
      { name: 'Cancelación', value: 'Activa 2x' },
      { name: 'Audio', value: 'Espacial personalizado' },
      { name: 'Resistencia', value: 'IPX4' },
      { name: 'Batería', value: '6h (30h con estuche)' },
    ],
    createdAt: '2025-02-05',
  },
  {
    id: 'airpods-max',
    name: 'AirPods Max',
    slug: 'airpods-max',
    description: 'AirPods Max con audio de alta fidelidad. Auriculares over-ear con cancelación activa de ruido, audio espacial con seguimiento dinámico y diseño ultracómodo con almohadillas de memory foam.',
    price: 2499999,
    category: 'Electrónica',
    categoryId: 'electronica',
    brand: 'Apple',
    model: 'AirPods Max',
    stock: 6,
    image: 'https://images.unsplash.com/photo-1556196148-1fb724238998?w=800&h=1000&fit=crop',
    specifications: [
      { name: 'Tipo', value: 'Over-ear' },
      { name: 'Cancelación', value: 'Activa' },
      { name: 'Audio', value: 'Espacial con seguimiento' },
      { name: 'Driver', value: 'Apple de 40mm' },
      { name: 'Batería', value: '20 horas' },
      { name: 'Peso', value: '385 g' },
    ],
    createdAt: '2025-01-20',
  },

  // ── Audio Profesional ───────────────────────────────────────
  {
    id: 'shure-sm7b',
    name: 'Shure SM7B',
    slug: 'shure-sm7b',
    description: 'Micrófono dinámico cardioide de estudio. El estándar de la industria para broadcasting, podcasting y grabación vocal. Con filtro pop integrado y respuesta de frecuencia plana y suave.',
    price: 1499999,
    category: 'Electrónica',
    categoryId: 'electronica',
    brand: 'Shure',
    model: 'SM7B',
    stock: 9,
    image: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=800&h=1000&fit=crop',
    specifications: [
      { name: 'Tipo', value: 'Dinámico' },
      { name: 'Patrón Polar', value: 'Cardioide' },
      { name: 'Respuesta', value: '50Hz - 20kHz' },
      { name: 'Impedancia', value: '150Ω' },
      { name: 'Filtro Pop', value: 'Integrado' },
      { name: 'Peso', value: '765 g' },
    ],
    createdAt: '2025-03-01',
  },
  {
    id: 'rode-nt-usb-mini',
    name: 'Rode NT-USB Mini',
    slug: 'rode-nt-usb-mini',
    description: 'Micrófono USB condensador con calidad de estudio. Diseño compacto con soporte de escritorio integrado, cápsula cardioide y monitoreo de auriculares sin latencia.',
    price: 599999,
    category: 'Electrónica',
    categoryId: 'electronica',
    brand: 'Rode',
    model: 'NT-USB Mini',
    stock: 18,
    image: 'https://images.unsplash.com/photo-1652071148620-99be24e731a8?ixlib=rb-4.1.0&q=85&fm=jpg&crop=entropy&cs=srgb&dl=tom-sid-0bRxK9kM3us-unsplash.jpg',
    specifications: [
      { name: 'Tipo', value: 'Condensador' },
      { name: 'Patrón Polar', value: 'Cardioide' },
      { name: 'Respuesta', value: '20Hz - 20kHz' },
      { name: 'Conexión', value: 'USB-C' },
      { name: 'Monitoreo', value: 'Sin latencia' },
      { name: 'Peso', value: '385 g' },
    ],
    createdAt: '2025-04-12',
  },
  {
    id: 'sony-wh-1000xm5',
    name: 'Sony WH-1000XM5',
    slug: 'sony-wh-1000xm5',
    description: 'Auriculares inalámbricos con cancelación de ruido líder en la industria. Procesador V1, audio de alta resolución, 30 horas de batería y llamadas con manos libres avanzadas.',
    price: 1299999,
    category: 'Electrónica',
    categoryId: 'electronica',
    brand: 'Sony',
    model: 'WH-1000XM5',
    stock: 22,
    image: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&h=1000&fit=crop',
    specifications: [
      { name: 'Tipo', value: 'Over-ear inalámbrico' },
      { name: 'Cancelación', value: 'Adaptativa líder' },
      { name: 'Driver', value: '30mm' },
      { name: 'Batería', value: '30 horas' },
      { name: 'Carga', value: 'USB-C, 3h a full' },
      { name: 'Peso', value: '250 g' },
    ],
    createdAt: '2025-02-28',
  },

  // ── Cámaras ─────────────────────────────────────────────────
  {
    id: 'dji-osmo-pocket-3',
    name: 'DJI Osmo Pocket 3',
    slug: 'dji-osmo-pocket-3',
    description: 'Cámara compacta con estabilización de 3 ejes. Sensor de 1 pulgada, grabación 4K a 120fps, pantalla táctil giratoria de 2 pulgadas y seguimiento inteligente de sujetos.',
    price: 1899999,
    category: 'Electrónica',
    categoryId: 'electronica',
    brand: 'DJI',
    model: 'Osmo Pocket 3',
    stock: 7,
    image: 'https://images.unsplash.com/photo-1715200811091-b7fc060667ff?ixlib=rb-4.1.0&q=85&fm=jpg&crop=entropy&cs=srgb&dl=alin-gavriliuc-PB_BvMzHcQ0-unsplash.jpg',
    specifications: [
      { name: 'Sensor', value: '1" CMOS' },
      { name: 'Video', value: '4K 120fps' },
      { name: 'Estabilización', value: '3 ejes mecánica' },
      { name: 'Pantalla', value: '2" táctil giratoria' },
      { name: 'Batería', value: 'Hasta 2 horas' },
      { name: 'Peso', value: '179 g' },
    ],
    createdAt: '2025-03-05',
  },
  {
    id: 'gopro-hero12-black',
    name: 'GoPro HERO12 Black',
    slug: 'gopro-hero12-black',
    description: 'Cámara de acción definitiva. Video 5.3K a 60fps, HyperSmooth 6.0 con estabilización 360°, resistente al agua hasta 10m sin carcasa y fotos de 27MP.',
    price: 1599999,
    category: 'Electrónica',
    categoryId: 'electronica',
    brand: 'GoPro',
    model: 'HERO12 Black',
    stock: 4,
    image: 'https://images.unsplash.com/photo-1703145204993-d1178bfc3f9f?ixlib=rb-4.1.0&q=85&fm=jpg&crop=entropy&cs=srgb&dl=duc-van-3nf8I6juiEE-unsplash.jpg',
    specifications: [
      { name: 'Video', value: '5.3K 60fps' },
      { name: 'Foto', value: '27MP' },
      { name: 'Estabilización', value: 'HyperSmooth 6.0' },
      { name: 'Resistencia', value: '10m sin carcasa' },
      { name: 'Batería', value: 'Enduro, 70min 5.3K' },
    ],
    createdAt: '2025-02-22',
  },

  // ── Deportes: Bicicletas ────────────────────────────────────
  {
    id: 'trek-fx-3-disc',
    name: 'Trek FX 3 Disc',
    slug: 'trek-fx-3-disc',
    description: 'Bicicleta híbrida de alto rendimiento. Cuadro de aluminio Alpha Gold, horquilla de carbono, transmisión Shimano Alivio de 18 velocidades y frenos de disco hidráulicos.',
    price: 4999999,
    category: 'Deportes',
    categoryId: 'deportes',
    brand: 'Trek',
    model: 'FX 3 Disc',
    stock: 3,
    image: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?ixlib=rb-4.1.0&q=85&fm=jpg&crop=entropy&cs=srgb&dl=kobus-carelse-w0Cb2eE8w7Y-unsplash.jpg',
    specifications: [
      { name: 'Cuadro', value: 'Aluminio Alpha Gold' },
      { name: 'Horquilla', value: 'Carbono' },
      { name: 'Transmisión', value: 'Shimano Alivio 18v' },
      { name: 'Frenos', value: 'Disco hidráulicos' },
      { name: 'Ruedas', value: '700c Bontrager' },
      { name: 'Peso', value: '10.5 kg' },
    ],
    createdAt: '2025-02-14',
  },
  {
    id: 'specialized-rockhopper',
    name: 'Specialized Rockhopper',
    slug: 'specialized-rockhopper',
    description: 'MTB de entrada con calidad superior. Cuadro A1 Premium Aluminio, suspensión SR Suntour XCR de 100mm, transmisión microSHIFT Advent X de 10 velocidades y frenos de disco hidráulicos.',
    price: 3799999,
    category: 'Deportes',
    categoryId: 'deportes',
    brand: 'Specialized',
    model: 'Rockhopper',
    stock: 5,
    image: 'https://images.unsplash.com/photo-1633707167682-9068729bc84c?ixlib=rb-4.1.0&q=85&fm=jpg&crop=entropy&cs=srgb&dl=axel-brunst-yr22qT5pqw4-unsplash.jpg',
    specifications: [
      { name: 'Cuadro', value: 'A1 Premium Aluminio' },
      { name: 'Suspensión', value: 'SR Suntour XCR 100mm' },
      { name: 'Transmisión', value: 'microSHIFT Advent X 10v' },
      { name: 'Frenos', value: 'Disco hidráulicos' },
      { name: 'Ruedas', value: '29" Specialized' },
      { name: 'Peso', value: '13.8 kg' },
    ],
    createdAt: '2025-01-30',
  },

  // ── Herramientas ────────────────────────────────────────────
  {
    id: 'bosch-taladro-18v',
    name: 'Taladro Bosch Professional 18V',
    slug: 'taladro-bosch-professional-18v',
    description: 'Taladro inalámbrico Professional GSR 18V-50. Mandril autoajustable de 13mm, velocidad variable, 2 marchas y batería de iones de litio. Ideal para construcción y bricolaje avanzado.',
    price: 899999,
    category: 'Herramientas',
    categoryId: 'herramientas',
    brand: 'Bosch',
    model: 'GSR 18V-50',
    stock: 16,
    image: 'https://images.unsplash.com/photo-1645651964715-d200ce0939cc?ixlib=rb-4.1.0&q=85&fm=jpg&crop=entropy&cs=srgb&dl=benjamin-lehman-EJU7A__krX0-unsplash.jpg',
    specifications: [
      { name: 'Voltaje', value: '18V' },
      { name: 'Mandril', value: '13mm autoajustable' },
      { name: 'Velocidad', value: 'Variable 2 marchas' },
      { name: 'Par', value: '50 Nm' },
      { name: 'Batería', value: 'Iones de litio 4.0Ah' },
      { name: 'Peso', value: '1.3 kg' },
    ],
    createdAt: '2025-04-01',
  },
  {
    id: 'dewalt-sierra-circular',
    name: 'DeWalt Sierra Circular 7¼"',
    slug: 'dewalt-sierra-circular-7-14',
    description: 'Sierra circular inalámbrica DeWalt DCS575. Motor sin escobillas, hoja de 7¼ pulgadas, guía láser y bisel hasta 57°. Máxima potencia para cortes precisos en obra.',
    price: 1299999,
    category: 'Herramientas',
    categoryId: 'herramientas',
    brand: 'DeWalt',
    model: 'DCS575',
    stock: 8,
    image: 'https://images.unsplash.com/photo-1642006953671-1bda5cd362ba?ixlib=rb-4.1.0&q=85&fm=jpg&crop=entropy&cs=srgb&dl=chris-kursikowski-tqO8XrNEvFw-unsplash.jpg',
    specifications: [
      { name: 'Hoja', value: '7¼" (184mm)' },
      { name: 'Motor', value: 'Sin escobillas' },
      { name: 'Bisel', value: '0° - 57°' },
      { name: 'Guía', value: 'Láser integrada' },
      { name: 'Batería', value: '18V XR 5.0Ah' },
      { name: 'Peso', value: '3.8 kg' },
    ],
    createdAt: '2025-03-18',
  },
  {
    id: 'makita-lijadora-orbital',
    name: 'Makita Lijadora Orbital',
    slug: 'makita-lijadora-orbital',
    description: 'Lijadora orbital aleatoria Makita BO5041. Diámetro de órbita de 5mm, sistema de extracción de polvo, velocidad variable y empuñadura ergonómica para acabados profesionales.',
    price: 699999,
    category: 'Herramientas',
    categoryId: 'herramientas',
    brand: 'Makita',
    model: 'BO5041',
    stock: 12,
    image: 'https://images.unsplash.com/photo-1689935421853-cb23a0bc92e4?ixlib=rb-4.1.0&q=85&fm=jpg&crop=entropy&cs=srgb&dl=fairuz-naufal-zaki-QQTDwZcRTRI-unsplash.jpg',
    specifications: [
      { name: 'Tipo', value: 'Orbital aleatoria' },
      { name: 'Órbita', value: '5mm' },
      { name: 'Velocidad', value: '4000-12000 OPM' },
      { name: 'Extracción', value: 'Polvo integrada' },
      { name: 'Plato', value: '125mm (5")' },
      { name: 'Peso', value: '1.6 kg' },
    ],
    createdAt: '2025-03-25',
  },

  // ── Hogar ──────────────────────────────────────────────────
  {
    id: 'dyson-v15-detect',
    name: 'Dyson V15 Detect',
    slug: 'dyson-v15-detect',
    description: 'Aspiradora inalámbrica Dyson V15 Detect. Láser revela polvo invisible, pantalla LCD muestra partículas, motor Hyperdymium con 240W de succión y hasta 60 minutos de autonomía.',
    price: 3299999,
    category: 'Hogar',
    categoryId: 'hogar',
    brand: 'Dyson',
    model: 'V15 Detect',
    stock: 6,
    image: 'https://images.unsplash.com/photo-1569698134101-f15cde5cd66c?ixlib=rb-4.1.0&q=85&fm=jpg&crop=entropy&cs=srgb&dl=lukas-ter-poorten-paAJDCYNq-0-unsplash.jpg',
    specifications: [
      { name: 'Succión', value: '240W (240AW)' },
      { name: 'Autonomía', value: 'Hasta 60 min' },
      { name: 'Filtración', value: 'HEPA completa' },
      { name: 'Tecnología', value: 'Laser Detect' },
      { name: 'Pantalla', value: 'LCD con conteo' },
      { name: 'Peso', value: '2.7 kg' },
    ],
    createdAt: '2025-02-20',
  },
  {
    id: 'philips-airfryer-xxl',
    name: 'Philips Airfryer XXL',
    slug: 'philips-airfryer-xxl',
    description: 'Freidora de aire Philips Airfryer XXL con tecnología Rapid Air. Capacidad para 2kg, 7 programas predefinidos, hasta 80% menos grasa y pantalla táctil digital.',
    price: 1199999,
    category: 'Hogar',
    categoryId: 'hogar',
    brand: 'Philips',
    model: 'Airfryer XXL',
    stock: 14,
    image: 'https://images.unsplash.com/photo-1559496417-e7f25cb247f3?ixlib=rb-4.1.0&q=85&fm=jpg&crop=entropy&cs=srgb&dl=bradley-pisney-p5gqicLi8LY-unsplash.jpg',
    specifications: [
      { name: 'Capacidad', value: '2kg (7 porciones)' },
      { name: 'Tecnología', value: 'Rapid Air' },
      { name: 'Programas', value: '7 predefinidos' },
      { name: 'Temperatura', value: '80°C - 200°C' },
      { name: 'Pantalla', value: 'Táctil digital' },
      { name: 'Potencia', value: '2000W' },
    ],
    createdAt: '2025-01-10',
  },
  {
    id: 'nespresso-vertuo-next',
    name: 'Nespresso Vertuo Next',
    slug: 'nespresso-vertuo-next',
    description: 'Cafetera Nespresso Vertuo Next. Tecnología Centrifusion que lee el código de barras de cada cápsula. Prepara 5 tamaños diferentes, desde espresso hasta café alto. Conexión WiFi y Bluetooth.',
    price: 699999,
    category: 'Hogar',
    categoryId: 'hogar',
    brand: 'Nespresso',
    model: 'Vertuo Next',
    stock: 20,
    image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?ixlib=rb-4.1.0&q=85&fm=jpg&crop=entropy&cs=srgb&dl=efe-kurnaz-vRc0B8lDsX4-unsplash.jpg',
    specifications: [
      { name: 'Sistema', value: 'Centrifusion' },
      { name: 'Tamaños', value: '5 (Espresso a Alto)' },
      { name: 'Depósito', value: '1.1L' },
      { name: 'Conectividad', value: 'WiFi + Bluetooth' },
      { name: 'Material', value: 'Plástico reciclado 54%' },
      { name: 'Peso', value: '3.8 kg' },
    ],
    createdAt: '2025-04-08',
  },
];
